<a href="https://colab.research.google.com/github/Nguyencaoquochuy/Nguy-n-Cao-Qu-c-Huy-CS441V-Data-Visualization-/blob/main/Baitap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1 Load và kiểm tra dataset

In [21]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Môn Thầy Hà/sales_data.csv')

In [30]:
df.head(5)

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method,total_amount
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card,1200
1,1002,2024-01-02,C002,Bob,Los Angeles,Headphones,Electronics,2,150,PayPal,300
2,1003,2024-01-03,C003,Charlie,New York,Office Chair,Furniture,1,350,Credit Card,350
3,1004,2024-01-03,C001,Alice,New York,Mouse,Electronics,3,25,Debit Card,75
4,1005,2024-01-04,C004,Diana,Chicago,Desk,Furniture,1,500,Bank Transfer,500
5,1006,2024-01-04,C005,Eve,Chicago,Laptop,Electronics,1,1100,Credit Card,1100
6,1007,2024-01-05,C002,Bob,Los Angeles,Monitor,Electronics,2,300,Debit Card,600
7,1008,2024-01-05,C003,Charlie,New York,Desk Lamp,Furniture,2,45,PayPal,90
8,1009,2024-01-06,C006,Frank,Miami,Tablet,Electronics,1,600,Credit Card,600
9,1010,2024-01-06,C001,Alice,New York,Keyboard,Electronics,1,80,Bank Transfer,80

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10 non-null     int64
 1   order_date      10 non-null     object
 2   customer_id     10 non-null     object
 3   customer_name   10 non-null     object
 4   city            10 non-null     object
 5   product         10 non-null     object
 6   category        10 non-null     object
 7   quantity        10 non-null     int64
 8   unit_price      10 non-null     int64
 9   payment_method  10 non-null     object
dtypes: int64(3), object(7)
memory usage: 932.0+ bytes

## Q2 Tạo cột mới cho tổng giá trị đơn hàng

In [24]:
df = df.assign(total_amount = df['quantity']*df['unit_price'])

In [25]:
df.assign()

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method,total_amount
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card,1200
1,1002,2024-01-02,C002,Bob,Los Angeles,Headphones,Electronics,2,150,PayPal,300
2,1003,2024-01-03,C003,Charlie,New York,Office Chair,Furniture,1,350,Credit Card,350
3,1004,2024-01-03,C001,Alice,New York,Mouse,Electronics,3,25,Debit Card,75
4,1005,2024-01-04,C004,Diana,Chicago,Desk,Furniture,1,500,Bank Transfer,500
5,1006,2024-01-04,C005,Eve,Chicago,Laptop,Electronics,1,1100,Credit Card,1100
6,1007,2024-01-05,C002,Bob,Los Angeles,Monitor,Electronics,2,300,Debit Card,600
7,1008,2024-01-05,C003,Charlie,New York,Desk Lamp,Furniture,2,45,PayPal,90
8,1009,2024-01-06,C006,Frank,Miami,Tablet,Electronics,1,600,Credit Card,600
9,1010,2024-01-06,C001,Alice,New York,Keyboard,Electronics,1,80,Bank Transfer,80

# Q3 Lọc các đơn hàng có giá trị cao

In [31]:
df_order_big = df[df['total_amount']>500]

In [33]:
df_order_big

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method,total_amount
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card,1200
5,1006,2024-01-04,C005,Eve,Chicago,Laptop,Electronics,1,1100,Credit Card,1100
6,1007,2024-01-05,C002,Bob,Los Angeles,Monitor,Electronics,2,300,Debit Card,600
8,1009,2024-01-06,C006,Frank,Miami,Tablet,Electronics,1,600,Credit Card,600

# Q4 Đếm số đơn hàng của mỗi khách hàng

In [52]:
orders_per_customer = df.groupby('customer_id')['order_id'].count()

In [53]:
orders_per_customer

customer_id
C001    3
C002    2
C003    2
C004    1
C005    1
C006    1
Name: order_id, dtype: int64

# Q5 Tính tổng chi tiêu của mỗi khách hàng

In [61]:
total_pay = df.groupby('customer_id').agg(total_spent=('total_amount', 'sum'))

In [62]:
total_pay

             total_spent
customer_id
C001                1355
C002                 900
C003                 440
C004                 500
C005                1100
C006                 600

# Q6 Phân tích doanh thu theo ngày

In [65]:
df = pd.read_csv("/content/drive/MyDrive/Môn Thầy Hà/sales_data.csv",parse_dates=["order_date"])
df['total_amount'] = df['quantity'] * df['unit_price']
daily_revenue = (df.groupby("order_date")["total_amount"].sum().sort_values())

In [66]:
daily_revenue

order_date
2024-01-03     425
2024-01-06     680
2024-01-05     690
2024-01-02    1500
2024-01-04    1600
Name: total_amount, dtype: int64

# Q7 Xếp hạng khách hàng theo mức chỉ tiêu

In [68]:
total_pay["rank"] = total_pay["total_spent"].rank(
    ascending=False)

In [69]:
total_pay

             total_spent  rank
customer_id
C001                1355   1.0
C002                 900   3.0
C003                 440   6.0
C004                 500   5.0
C005                1100   2.0
C006                 600   4.0