# Setup environment and load data

Dataset: https://s3.hothienlac.com/yomitoon/sales_data.csv

In [2]:
import pandas as pd

In [ ]:
# install xlrd
!pip install xlrd

print('xlrd installed!')

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
xlrd installed!

# 🟢 LEVEL 1 — Basic Data Understanding (Score 1–3)

## **Q1. Load and inspect the dataset**

### Task

Load the CSV file and:

1. Display the first 5 rows
2. Show column names and data types

### 💡 Hint

Use:

* `pd.read_csv`
* `.head()`
* `.info()`

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)
* [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)

### 🧠 Explanation

You are learning how to **inspect unfamiliar data** quickly and verify that Pandas interpreted types correctly (dates, numbers, strings).

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
raw_data = pd.read_csv('/content/drive/MyDrive/CS441V_Data visualization/sales_data.csv')

In [ ]:
raw_data.head()

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card
1,1002,2024-01-02,C002,Bob,Los Angeles,Headphones,Electronics,2,150,PayPal
2,1003,2024-01-03,C003,Charlie,New York,Office Chair,Furniture,1,350,Credit Card
3,1004,2024-01-03,C001,Alice,New York,Mouse,Electronics,3,25,Debit Card
4,1005,2024-01-04,C004,Diana,Chicago,Desk,Furniture,1,500,Bank Transfer

In [ ]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10 non-null     int64
 1   order_date      10 non-null     object
 2   customer_id     10 non-null     object
 3   customer_name   10 non-null     object
 4   city            10 non-null     object
 5   product         10 non-null     object
 6   category        10 non-null     object
 7   quantity        10 non-null     int64
 8   unit_price      10 non-null     int64
 9   payment_method  10 non-null     object
dtypes: int64(3), object(7)
memory usage: 932.0+ bytes

## **Q2. Create a new column for total order value**

### Task

Create a new column called `total_amount`
Formula:

```
quantity × unit_price
```

### 💡 Hint

Use:

* `.assign()`

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.assign.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.assign.html)

### 🧠 Explanation

This teaches **feature engineering** and the **functional Pandas mindset** (`inplace=False`, return a new DataFrame).

In [ ]:
total_amount = raw_data.assign(
    total_amount = raw_data["quantity"] * raw_data["unit_price"]
)

In [ ]:
total_amount.head()

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method,total_amount
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card,1200
1,1002,2024-01-02,C002,Bob,Los Angeles,Headphones,Electronics,2,150,PayPal,300
2,1003,2024-01-03,C003,Charlie,New York,Office Chair,Furniture,1,350,Credit Card,350
3,1004,2024-01-03,C001,Alice,New York,Mouse,Electronics,3,25,Debit Card,75
4,1005,2024-01-04,C004,Diana,Chicago,Desk,Furniture,1,500,Bank Transfer,500

# 🟡 LEVEL 2 — Filtering & Simple Analysis (Score 4–6)

## **Q3. Filter high-value orders**

### Task

Select only orders where:

* `total_amount > 500`

### 💡 Hint

Use **one** of:

* `.query()`
* Boolean indexing (`df[condition]`)

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)

### 🧠 Explanation

Filtering is the foundation of **real data analysis**.
You learn how Pandas handles **boolean logic**.

In [ ]:
filtered_df = total_amount[total_amount["total_amount"] > 500]

In [ ]:
filtered_df.head()

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,payment_method,total_amount
0,1001,2024-01-02,C001,Alice,New York,Laptop,Electronics,1,1200,Credit Card,1200
5,1006,2024-01-04,C005,Eve,Chicago,Laptop,Electronics,1,1100,Credit Card,1100
6,1007,2024-01-05,C002,Bob,Los Angeles,Monitor,Electronics,2,300,Debit Card,600
8,1009,2024-01-06,C006,Frank,Miami,Tablet,Electronics,1,600,Credit Card,600

## **Q4. Count how many orders each customer made**

### Task

Create a table showing:

* `customer_id`
* number of orders per customer

### 💡 Hint

Use:

* `.groupby()`
* `.count()` **or** `.size()`

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

### 🧠 Explanation

You learn how Pandas **splits data into groups** and applies calculations per group.

In [ ]:
orders_per_customer = (
    total_amount.groupby("customer_id")
      .size()
      .reset_index(name="order_count")
)

In [ ]:
orders_per_customer = (
  total_amount.groupby("customer_id")["order_id"]
      .count()
      .reset_index(name="order_count")
)

In [ ]:
orders_per_customer.head()

  customer_id  order_count
0        C001            3
1        C002            2
2        C003            2
3        C004            1
4        C005            1

# 🔴 LEVEL 3 — Aggregation & Time Awareness (Score 7–10)

## **Q5. Calculate total spending per customer**

### Task

For each `customer_id`, compute:

* Total money spent

### 💡 Hint

Use:

* `.groupby()`
* `.agg()`

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html)

### 🧠 Explanation

This introduces **aggregation pipelines** and prepares you for more complex analytics.

In [ ]:
total_spent_per_customer = (
    total_amount.groupby("customer_id")
      .agg(total_spent=("total_amount", "sum"))
      .reset_index()
)

In [ ]:
total_spent_per_customer.head()

  customer_id  total_spent
0        C001         1355
1        C002          900
2        C003          440
3        C004          500
4        C005         1100

## **Q6. Daily revenue analysis**

### Task

Calculate:

1. Total revenue per day
2. Sort results by date

### 💡 Hint

Use:

* `parse_dates` in `read_csv`
* `.groupby()`
* `.sort_values()`

### 📚 Reference

* [https://pandas.pydata.org/docs/user_guide/timeseries.html](https://pandas.pydata.org/docs/user_guide/timeseries.html)

### 🧠 Explanation

Time-based grouping is essential for **business dashboards and reports**.

In [ ]:
df = pd.read_csv("https://s3.hothienlac.com/yomitoon/sales_data.csv",
    parse_dates=["order_date"]
)

In [ ]:
df = df.assign(total_amount = df['quantity'] * df['unit_price'])
revenue_per_day = (
    df.groupby("order_date")
      .agg(total_revenue=("total_amount", "sum"))
)

In [ ]:
revenue_per_day = revenue_per_day.sort_values("order_date")

In [ ]:
revenue_per_day.head()

   index order_date  total_revenue
0      0 2024-01-02           1500
1      1 2024-01-03            425
2      2 2024-01-04           1600
3      3 2024-01-05            690
4      4 2024-01-06            680

## **Q7. Rank customers by spending**

### Task

Rank customers from highest to lowest total spending.

### 💡 Hint

Use:

* `.rank()`

### 📚 Reference

* [https://pandas.pydata.org/docs/reference/api/pandas.Series.rank.html](https://pandas.pydata.org/docs/reference/api/pandas.Series.rank.html)

### 🧠 Explanation

Ranking teaches you how Pandas handles **ordering, ties, and numeric comparisons**.

---

In [ ]:
total_spent_per_customer

  customer_id  total_spent
0        C001         1355
1        C002          900
2        C003          440
3        C004          500
4        C005         1100
5        C006          600

In [ ]:
ranked_customers = total_spent_per_customer.assign(
    spending_rank = total_spent_per_customer["total_spent"]
        .rank(ascending=False, method="dense")
)

In [ ]:
ranked_customers = ranked_customers.sort_values("spending_rank")

In [ ]:
ranked_customers.head()

  customer_id  total_spent  spending_rank
0        C001         1355            1.0
4        C005         1100            2.0
1        C002          900            3.0
5        C006          600            4.0
3        C004          500            5.0

# 🎯 Learning Outcome by Level

| Level | You can now…                             |
| ----- | ---------------------------------------- |
| 1     | Load, inspect, create columns            |
| 2     | Filter and group data                    |
| 3     | Aggregate, rank, and analyze time series |